from enum import Enum

class SysControlCommands(Enum):
    NOP = 0
    GETSTATUS = 1
    RESETSTATIONS = 15
    SCANRESULTS = 16
    CALIBRATESTATIONS = 17
    STATIONORDER = 18
    RECEIVESCAPP = 20
    RECEIVETFAPP = 21
    EXITBOOTLOADER = 22
    ERASEFLASH = 23
    SCSTARTBOOT = 0x44
    SCSTARTMAIN = 0x45
    SCGETSTATUS = 0x46


